// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University.Infrastructure;

#nullable disable

namespace University.Infrastructure.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20251228152824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("University.Infrastructure.Models.GroupModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("University.Infrastructure.Models.PersonModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PersonModel");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("University.Infrastructure.Models.StudentModel", b =>
                {
                    b.HasBaseType("University.Infrastructure.Models.PersonModel");

                    b.Property<int>("Course")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("University.Infrastructure.Models.TeacherModel", b =>
                {
                    b.HasBaseType("University.Infrastructure.Models.PersonModel");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("University.Infrastructure.Models.StudentModel", b =>
                {
                    b.HasOne("University.Infrastructure.Models.GroupModel", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Infrastructure.Models.PersonModel", null)
                        .WithOne()
                        .HasForeignKey("University.Infrastructure.Models.StudentModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("University.Infrastructure.Models.TeacherModel", b =>
                {
                    b.HasOne("University.Infrastructure.Models.PersonModel", null)
                        .WithOne()
                        .HasForeignKey("University.Infrastructure.Models.TeacherModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("University.Infrastructure.Models.GroupModel", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
